AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple Serverless App

Resources:
  # ----------------------------------------------------------------------------
  # Click Function
  # ----------------------------------------------------------------------------
  LandingPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: landing-page-function/
      Handler: landing_page_function.lambda_handler
      Runtime: python3.8
      Events:
        GetLandingPage:
          Type: HttpApi
          Properties:
            Path: /
            Method: get

  # ----------------------------------------------------------------------------
  # Click Function
  # ----------------------------------------------------------------------------
  ClickFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: click-function/
      Handler: click_function.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /click
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref ClickTable            
      Policies:
      - AmazonDynamoDBFullAccess
 
  # ----------------------------------------------------------------------------
  # Click Table
  # ----------------------------------------------------------------------------
  ClickTable:
    Type: AWS::Serverless::SimpleTable